import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react";
import { Sidebar } from "lucide-react";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { useState } from "react";

const dyslexiaFont = localFont({
  src: [
    {
      path: "../../public/fonts/OpenDyslexic-Regular.woff2", // Use the correct path relative to /public
      weight: "normal", // optional, specify the weight if applicable
      style: "normal", // optional, specify the style
    },
  ],
});

export const metadata: Metadata = {
  title: "DyslexiRead",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dyslexiaFont.className} antialiased bg-[#FFF7EF] text-[#020402]`}
      >
        {" "}
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          {children}
          <Analytics />
        </SidebarProvider>
      </body>
    </html>
  );
}
